variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - analysis
  - build
  - test

before_script:
  - hostname
  - whoami
# - pwd

analysis-cppcheck:
  stage: analysis
  variables:
    GIT_SUBMODULE_STRATEGY: none
  artifacts:
    name: analysis-cppcheck-logs
    when: always
    paths:
      - cppcheck/
  tags:
    - cppcheck
  script:
    - ./ci/analysis-cppcheck.sh

build-linux-gcc:
  stage: build
  tags:
    - linux
    - gcc
    - cmake
    - x86
    - uhd
  artifacts:
    name: build-linux-gcc
    when: always
    paths:
      - ./build_linux_gcc/
  script:
    - export CXX="g++"
    - export CFLAGS="-Wall -funroll-loops -mavx2"
    - export BUILD="build_linux_gcc"
    - source ./ci/tools/threads.sh
    - ./ci/build-linux-macos.sh

build-linux-clang:
  stage: build
  tags:
    - linux
    - clang
    - cmake
    - x86
    - uhd
  artifacts:
    name: build-linux-clang
    when: always
    paths:
      - ./build_linux_clang/
  script:
    - export CXX="clang++"
    - export CFLAGS="-Wall -Wno-overloaded-virtual -funroll-loops -msse4.2"
    - export BUILD="build_linux_clang"
    - source ./ci/tools/threads.sh
    - ./ci/build-linux-macos.sh

build-linux-gcc-4.8:
  stage: build
  tags:
    - linux
    - gcc-4.8
    - cmake
  artifacts:
    name: build-linux-gcc-4.8
    when: always
    paths:
      - ./build_linux_gcc-4.8/
  script:
    - export CXX="g++-4.8"
    - export CFLAGS="-Wall -funroll-loops -msse4.2"
    - export CMAKE_OPT="-DDVBS2O_LINK_UHD=OFF"
    - export BUILD="build_linux_gcc-4.8"
    - source ./ci/tools/threads.sh
    - ./ci/build-linux-macos.sh

# build-linux-icpc:
#   stage: build
#   tags:
#     - linux
#     - icpc
#     - cmake
#     - x86
#     - uhd
#   artifacts:
#     name: build-linux-icpc
#     when: always
#     paths:
#       - ./build_linux_icpc/
#   script:
#     - export CXX="icpc"
#     - export CFLAGS="-Wall -funroll-loops -msse4.2 -std=c++11"
#     - export BUILD="build_linux_icpc"
#     - source ./ci/tools/threads.sh
#     - ./ci/build-linux-macos.sh

build-windows-gcc:
  stage: build
  tags:
    - windows
    - gcc
    - cmake
  artifacts:
    name: build-windows-gcc
    when: always
    paths:
      - ./build_windows_gcc/
  script:
    - set "CFLAGS=-Wall -funroll-loops -mavx"
    - set "BUILD=build_windows_gcc"
    - set "CMAKE_OPT=-DDVBS2O_LINK_UHD=OFF"
    - call ./ci/tools/threads.bat
    - ./ci/build-windows-gcc.bat

build-windows-msvc:
  stage: build
  tags:
    - windows
    - msvc
    - cmake
  artifacts:
    name: build-windows-msvc
    when: always
    paths:
      - ./build_windows_msvc/
  script:
    - set "CFLAGS=-D_CRT_SECURE_NO_DEPRECATE /EHsc /arch:AVX"
    - set "BUILD=build_windows_msvc"
    - set "CMAKE_OPT=-DDVBS2O_LINK_UHD=OFF"
    - call ./ci/tools/threads.bat
    - ./ci/build-windows-msvc.bat

build-macos-clang:
  stage: build
  tags:
    - macos
    - apple-clang
    - cmake
    - x86
    - uhd
  artifacts:
    name: build-macos-clang
    when: always
    paths:
      - ./build_macos_clang/
  script:
    - export CXX="clang++"
    - export CFLAGS="-Wall -Wno-overloaded-virtual -funroll-loops -msse4.2"
    - export BUILD="build_macos_clang"
    - source ./ci/tools/threads.sh
    - ./ci/build-linux-macos.sh

test-regression-tx-rx-bb:
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  retry: 1
  dependencies:
    - build-linux-gcc
  tags:
    - linux
    - x86
    - 64-bit
    - avx2
    - python3.4
    - powerful
  artifacts:
     name: test-regression-results-tx-rx-bb
     when: always
     paths:
      - test-regression-results-tx-rx-bb/
  script:
    - source ./ci/tools/threads.sh
    - export OMP_NUM_THREADS=$THREADS
    - export TIME_SEC="5"
    - ./lib/aff3ct/ci/test-regression.py --refs-path refs/TX_RX_BB/ --results-path test-regression-results-tx-rx-bb --build-path build_linux_gcc --binary-path bin/dvbs2_optique_tx_rx_bb --max-snr-time $TIME_SEC --sensibility 2.5 --weak-rate 0.9 --verbose 1

# test-regression-tx-rx:
#   stage: test
#   variables:
#     GIT_SUBMODULE_STRATEGY: recursive
#   retry: 1
#   dependencies:
#     - build-linux-gcc
#   tags:
#     - linux
#     - x86
#     - 64-bit
#     - sse4.2
#     - python3.4
#     - powerful
#   artifacts:
#      name: test-regression-results-tx-rx
#      when: always
#      paths:
#       - test-regression-results-tx-rx/
#   script:
#     - source ./ci/tools/threads.sh
#     - export OMP_NUM_THREADS=$THREADS
#     - export TIME_SEC="5"
#     - ./lib/aff3ct/ci/test-regression.py --refs-path refs/TX_RX/ --results-path test-regression-results-tx-rx --build-path build_linux_gcc --binary-path bin/dvbs2_optique_tx_rx --max-snr-time $TIME_SEC --sensibility 2.5 --weak-rate 0.9 --verbose 1
